# Generated by Django 3.2 on 2022-06-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0003_alter_modulo_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='nombre',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
