# Generated by Django 3.2 on 2022-06-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0004_alter_modulo_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitacion',
            name='nombre',
            field=models.CharField(max_length=400),
        ),
    ]
