# Generated by Django 3.2 on 2022-06-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0005_alter_capacitacion_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='temas',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
