# Generated by Django 3.2 on 2022-06-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0006_alter_modulo_temas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitacion',
            name='objetivo',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
